# -*- coding: utf-8 -*-
"""Week2Advanced_Algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LarYU0mKCzxLOGzdA--JFpTYMf7gwco7

Apolo BARNABAS
Week2 Advanced Algorithm
"""

#Copy this code, and create a program that finds,
#within list_of_numbers all the pairs of number that sum to the target number

import random

# Generate data
list_of_numbers = [random.randint(0, 10000) for _ in range(20000)]
target = random.randint(0, 20000)

# the pairs
seen = set()
pairs = set()  # to avoid duplicates

for num in list_of_numbers:
    complement = target - num

    if complement in seen:
        # store as a sorted tuple to avoid (a,b) and (b,a)
        pairs.add(tuple(sorted((num, complement))))

    seen.add(num)

# the results
print(f"Target: {target}")
print("Pairs that sum to target:")

for pair in pairs:
    print(pair)